name: Tribox action

on:
  schedule:
    - cron: "0 0 * * 0,3" # Runs every Wednesday and Sunday
  workflow_dispatch:

jobs:
  send-http-request:
    runs-on: ubuntu-latest

    steps:
    - name: Send HTTP Request to Weekly Query
      run: curl https://tribox-commerce.vercel.app/api/etc/weekly-query

    - name: Send HTTP Request to Home Page
      run: curl https://tribox-commerce.vercel.app/
